apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-telemetry-collector
  labels:
    app: open-telemetry
  namespace: open-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-telemetry
  template:
    metadata:
      labels:
        app: open-telemetry
    spec:
      serviceAccountName: open-telemetry
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: open-telemetry-collector
        env:
        - name: NO_PROXY
          value: 127.0.0.1,10.42.*,10.43.*,cluster.local
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: otel/opentelemetry-collector-contrib:0.116.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /etc/otel/config.yaml
          name: otelconfig
          subPath: config.yaml
          readOnly: true
        - mountPath: /otel-file
          name: otel-collector-pvc
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true  
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - configMap:
          defaultMode: 420
          name: otelcol
          optional: true
        name: otelconfig
      - name: otel-collector-pvc
        persistentVolumeClaim:
          claimName: otel-collector-pvc
