apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-collector-pvc
  labels:
    app: open-telemetry
  namespace: open-telemetry
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path