apiVersion: v1
kind: Service
metadata:
  name: open-telemetry-collector
  labels:
    app: open-telemetry
  namespace: open-telemetry
spec:
  type: ClusterIP
  ports:
    - name: otel
      port: 4317
    - name: prometheus
      port: 8080
  selector:
    app: open-telemetry
